### ISSUE TITLE
Error modifying or accessing schedule edit modal

### ISSUE THREAD

**Issue by jonathan-mothership** [grafana/oncall#1041]
Today we're not able to click into schedules, receiving the following message for all schedule edits (url in browser at time is `/a/grafana-oncall-app/?page=incidents`):

```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'action')

    at p (/public/plugins/grafana-oncall-app/module.js:2:1382199)
    at p (/public/plugins/grafana-oncall-app/module.js:2:1382199)
    at n (/public/plugins/grafana-oncall-app/module.js:2:1387123)
    at t (/public/build/2754.c9252327f51106ea3a6d.js:2:1050081)
    at io (/public/build/2352.d7c14cbd3dbda648a17f.js:8778:23756)
    at component
    at Suspense
    at c (/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at _c (/public/build/2352.d7c14cbd3dbda648a17f.js:8832:350)
    at t (/public/build/2754.c9252327f51106ea3a6d.js:2:1060624)
    at t (/public/build/2754.c9252327f51106ea3a6d.js:2:1062645)
    at main
    at Cd (/public/build/2352.d7c14cbd3dbda648a17f.js:8793:6820)
    at t (/public/build/2754.c9252327f51106ea3a6d.js:2:1057242)
    at div
    at o (/public/build/2352.d7c14cbd3dbda648a17f.js:1996:4308)
    at t.KBarProvider (/public/build/2754.c9252327f51106ea3a6d.js:2:271053)
    at l (/public/build/2352.d7c14cbd3dbda648a17f.js:6145:19538)
    at c (/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at u (/public/build/2352.d7c14cbd3dbda648a17f.js:1207:855)
    at l (/public/build/2754.c9252327f51106ea3a6d.js:2:1040276)
    at bu (/public/build/2352.d7c14cbd3dbda648a17f.js:8845:115)
```
```

**Comment by jonathan-mothership** [comment]
We seem to be able to bypass this bug by clicking instead on the name of the schedule rather than the calendar bars. Not critical in the end and we're able to manage our schedules despite this.

**Comment by maskin25** [comment]
@jonathan-mothership hi, thanks for reporting, can you confirm the bug has gone? Recently we fixed several similar bugs in Schedules UI, so I suppose this one was fixed too
