### ISSUE TITLE
Container doesn't properly start when MySQL is not available

### ISSUE THREAD

**Issue by roock** [grafana/oncall#1194]
The oncall container doesn't properly start when MySQL is not (yet) available. I've only tested this issue with the docker-compose stack (mysql+rabbitmy). I think this could be a docker-compose specific issue and not relevant for kubernetes setups, since in kubernetes the mysql service would resolve even if the database is not (yet) ready.

Log output:
```
[log-encoder] registered format ${strftime:%Y-%m-%d %H:%M:%S} ${msgnl}
2023-01-23 15:28:38 *** Starting uWSGI 2.0.20 (64bit) on [Mon Jan 23 15:28:33 2023] ***
2023-01-23 15:28:38 compiled with version: 8.3.0 on 18 January 2023 20:13:01
2023-01-23 15:28:38 os: Linux-5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:50 UTC 2022
2023-01-23 15:28:38 nodename: 01d31400f874
2023-01-23 15:28:38 machine: aarch64
2023-01-23 15:28:38 clock source: unix
2023-01-23 15:28:38 detected number of CPU cores: 4
2023-01-23 15:28:38 current working directory: /etc/app
2023-01-23 15:28:38 writing pidfile to /tmp/project-master.pid
2023-01-23 15:28:38 detected binary path: /usr/local/bin/uwsgi
2023-01-23 15:28:38 !!! no internal routing support, rebuild with pcre support !!!
2023-01-23 15:28:38 uWSGI running as root, you can use --uid/--gid/--chroot options
2023-01-23 15:28:38 setgid() to 2000
2023-01-23 15:28:38 setuid() to 1000
2023-01-23 15:28:38 chdir() to /etc/app
2023-01-23 15:28:38 your memory page size is 4096 bytes
2023-01-23 15:28:38 detected max file descriptor number: 1048576
2023-01-23 15:28:38 lock engine: pthread robust mutexes
2023-01-23 15:28:38 thunder lock: disabled (you can enable it with --thunder-lock)
2023-01-23 15:28:38 uWSGI http bound on 0.0.0.0:8080 fd 7
2023-01-23 15:28:38 uwsgi socket 0 bound to TCP address 127.0.0.1:42421 (port auto-assigned) fd 6
2023-01-23 15:28:38 Python version: 3.9.16 (main, Jan 18 2023, 02:33:26)  [GCC 8.3.0]
2023-01-23 15:28:38 *** Python threads support is disabled. You can enable it with --enable-threads ***
2023-01-23 15:28:38 Python main interpreter initialized at 0xaaab0d5caed0
2023-01-23 15:28:38 your server socket listen backlog is limited to 100 connections
2023-01-23 15:28:38 your mercy for graceful operations on workers is 60 seconds
2023-01-23 15:28:38 mapped 855210 bytes (835 KB) for 5 cores
2023-01-23 15:28:38 *** Operational MODE: preforking ***
2023-01-23 15:28:38 Traceback (most recent call last):
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 613, in connect
2023-01-23 15:28:38     sock = socket.create_connection(
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/socket.py", line 823, in create_connection
2023-01-23 15:28:38     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
2023-01-23 15:28:38     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-01-23 15:28:38 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-01-23 15:28:38 
During handling of the above exception, another exception occurred:
2023-01-23 15:28:38 Traceback (most recent call last):
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-01-23 15:28:38     self.connect()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-01-23 15:28:38     self.connection = self.get_new_connection(conn_params)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
2023-01-23 15:28:38     connection = Database.connect(**conn_params)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
2023-01-23 15:28:38     self.connect()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 664, in connect
2023-01-23 15:28:38     raise exc
2023-01-23 15:28:38 pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno -3] Temporary failure in name resolution)")
2023-01-23 15:28:38 
The above exception was the direct cause of the following exception:
2023-01-23 15:28:38 Traceback (most recent call last):
2023-01-23 15:28:38   File "/etc/app/./engine/__init__.py", line 5, in <module>
2023-01-23 15:28:38     from .celery import app as celery_app
2023-01-23 15:28:38   File "/etc/app/./engine/celery.py", line 24, in <module>
2023-01-23 15:28:38     connection.cursor()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
2023-01-23 15:28:38     return self._cursor()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
2023-01-23 15:28:38     self.ensure_connection()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-01-23 15:28:38     self.connect()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2023-01-23 15:28:38     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-01-23 15:28:38     self.connect()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-01-23 15:28:38     self.connection = self.get_new_connection(conn_params)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
2023-01-23 15:28:38     return func(*args, **kwargs)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
2023-01-23 15:28:38     connection = Database.connect(**conn_params)
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
2023-01-23 15:28:38     self.connect()
2023-01-23 15:28:38   File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 664, in connect
2023-01-23 15:28:38     raise exc
2023-01-23 15:28:38 django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno -3] Temporary failure in name resolution)")
2023-01-23 15:28:38 unable to load app 0 (mountpoint='') (callable not found or import error)
2023-01-23 15:28:38 *** no app loaded. going in full dynamic mode ***
2023-01-23 15:28:38 *** uWSGI is running in multiple interpreter mode ***
2023-01-23 15:28:38 spawned uWSGI master process (pid: 7)
2023-01-23 15:28:38 spawned uWSGI worker 1 (pid: 8, cores: 1)
2023-01-23 15:28:38 spawned uWSGI worker 2 (pid: 9, cores: 1)
2023-01-23 15:28:38 spawned uWSGI worker 3 (pid: 10, cores: 1)
2023-01-23 15:28:38 spawned uWSGI worker 4 (pid: 11, cores: 1)
2023-01-23 15:28:38 spawned uWSGI worker 5 (pid: 12, cores: 1)
2023-01-23 15:28:38 spawned uWSGI http 1 (pid: 13)
2023-01-23 15:35:15 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:15 source=engine:uwsgi status=500 method=GET path=/ latency=0.000490 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:20 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:20 source=engine:uwsgi status=500 method=GET path=/ latency=0.000251 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:20 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:20 source=engine:uwsgi status=500 method=GET path=/favicon.ico latency=0.000135 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:59 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:59 source=engine:uwsgi status=500 method=GET path=/ latency=0.000099 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:59 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:59 source=engine:uwsgi status=500 method=GET path=/favicon.ico latency=0.000052 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:59 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:59 source=engine:uwsgi status=500 method=GET path=/ latency=0.000148 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:35:59 --- no python application found, check your startup logs for errors ---
2023-01-23 15:35:59 source=engine:uwsgi status=500 method=GET path=/favicon.ico latency=0.000081 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:36:00 --- no python application found, check your startup logs for errors ---
2023-01-23 15:36:00 source=engine:uwsgi status=500 method=GET path=/ latency=0.000749 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:36:00 --- no python application found, check your startup logs for errors ---
2023-01-23 15:36:00 source=engine:uwsgi status=500 method=GET path=/favicon.ico latency=0.000034 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:36:00 --- no python application found, check your startup logs for errors ---
2023-01-23 15:36:00 source=engine:uwsgi status=500 method=GET path=/ latency=0.000058 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:36:00 --- no python application found, check your startup logs for errors ---
2023-01-23 15:36:00 source=engine:uwsgi status=500 method=GET path=/favicon.ico latency=0.000040 google_trace_id=- protocol=HTTP/1.1 resp_size=104 req_body_size=0
2023-01-23 15:36:00 --- no python application found, check your startup logs for errors ---
```

Even if mysql service is available again, the oncall service will not recover and needs to be restarted.
This does not occur when a new docker-compose stack is deployed, because it will honor the service dependencies outlined inside the coker-compose file. But in some other scenarios e.g. the server hosting the docker-compose stack is rebooted, the start order of the docker containers will be wrong and  the services  will fail to properly start and needs to be restarted, once the database is available.

I've tested a workaround by adding a container entrypoint to the Dockerfile to wait until the database is ready, but I think the root cause should be fixed/investigated too.

**Comment by joeyorlando** [comment]
Hi @roock 👋 what version of `docker-compose` are you using? Any chance you're running `<2.10`?

**Comment by roock** [comment]
@joeyorlando I'm on docker-compose version 2.15.1 and docker 20.10.23. The issue is also not happening when starting the docker-compose stack with `docker-compose up -d`, but when the docker service (re)starts since, it ignores the `service_healthy` conditions set by docker-compose in the container label `com.docker.compose.depends_on`.

I also tried to add health checks to the docker-compose file, but docker will only report the container health and not restart containers when they are unhealthy. Docker swarm would be required to restart containers based on their health.
