### ISSUE TITLE
Schedules page can't load the on-call calendars

### ISSUE THREAD

**Issue by khanhtran1991** [grafana/oncall#1338]
Today, I'm facing an issue that I can't see any on-call calendars. It keeps loading and shows `500` error. Is it a real bug?
Please help me to check it. I'm looking forward to hearing from you. 
Thank you so much!
![Screenshot from 2023-02-17 10-32-39](https://user-images.githubusercontent.com/100182792/219545605-105a6be3-c97a-4505-b7d6-ab76d05460d1.png)

**Comment by vadimkerr** [comment]
Hi @khanhtran1991, thank you for opening the issue!
Which version of Grafana OnCall are you running? Could you please also share some engine logs when trying to load the page?

**Comment by khanhtran1991** [comment]
Hi @vadimkerr, thanks for your replying.

- I'm using Grafana OnCall v1.1.14.

- Actually, there is no engine log for it. When I open **Schedules** page, it keeps loading and no calendar is shown.
Network logs show that it gets 500 error code when loading URL below:
`https://grafana.manabie.io/api/plugin-proxy/grafana-oncall-app/api/internal/v1/schedules/?search=`
![Screenshot from 2023-02-17 17-14-23](https://user-images.githubusercontent.com/100182792/219616766-824fb8b2-46d9-4a4c-a812-e9ae714322c5.png)

**Comment by khanhtran1991** [comment]
One more update, when I create a new team and schedule a new on-call calendar, it works and shows the calendar.
Only the General team has this issue.

**Comment by Matvey-Kuk** [comment]
@khanhtran1991 we really need backend's trace-logs to fix that. Could you please share them from the "engine" pod?

**Comment by khanhtran1991** [comment]
Hello @vadimkerr @Matvey-Kuk, understood your requirement.
Please find the attached CSV for more detail. I've found some error logs in the pod as below:
[grafana-oncall--logs-20230218-091321.csv](https://github.com/grafana/oncall/files/10772862/grafana-oncall--logs-20230218-091321.csv)

```
2023-02-18 02:04:48 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/schedules"

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_polymorphic/serializers.py", line 60, in to_representation
    ret = serializer.to_representation(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1882, in to_representation
    return method(value)
  File "/etc/app/apps/api/serializers/schedule_base.py", line 70, in get_on_call_now
    users_on_call = list_users_to_notify_from_ical(obj, timezone.datetime.now(timezone.utc))
  File "/etc/app/apps/schedules/ical_utils.py", line 290, in list_users_to_notify_from_ical
    return list_users_to_notify_from_ical_for_period(
  File "/etc/app/apps/schedules/ical_utils.py", line 306, in list_users_to_notify_from_ical_for_period
    events = ical_events.get_events_from_ical_between(calendar, start_datetime, end_datetime)
  File "/etc/app/apps/schedules/ical_events/proxy/ical_proxy.py", line 24, in get_events_from_ical_between
    return self.ical_adapter.get_events_from_ical_between(calendar, start_date, end_date)
  File "/etc/app/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py", line 102, in get_events_from_ical_between
    events = AmixrUnfoldableCalendar(calendar).between(
  File "/etc/app/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py", line 85, in between
    if repetition.is_in_span(span_start, span_stop):
  File "/usr/local/lib/python3.9/site-packages/recurring_ical_events.py", line 129, in is_in_span
    return time_span_contains_event(span_start, span_stop, self.start, self.stop)
  File "/usr/local/lib/python3.9/site-packages/recurring_ical_events.py", line 76, in time_span_contains_event
    assert event_start <= event_stop, "the event must start before it ends"
AssertionError: the event must start before it ends

2023-02-18 02:04:48 source=engine:app google_trace_id=none logger=root inbound latency=0.657685 status=500 method=GET path=/api/internal/v1/schedules content-length=0 slow=0 user_id=44 org_id=1

2023-02-18 02:04:48 source=engine:uwsgi status=500 method=GET path=/api/internal/v1/schedules?search= latency=0.658672 google_trace_id=- protocol=HTTP/1.1 resp_size=329 req_body_size=0
```

**Comment by Matvey-Kuk** [comment]
@khanhtran1991 thank you for the tracelog! @matiasb could you please check this one?

**Comment by khanhtran1991** [comment]
Hello @Matvey-Kuk @matiasb, good day!
Sorry for mentioning you. May I ask you about the status of this issue?

**Comment by matiasb** [comment]
hey @khanhtran1991!
I will be taking a closer look today. To be sure, did you try the latest oncall version (today, [v1.1.28](https://github.com/grafana/oncall/releases/tag/v1.1.28))? I think there were some fixes around a similar issue but it may have been in a later release.

**Comment by khanhtran1991** [comment]
@matiasb Hello, I've updated to the latest version and it really helps. It's fine now.
Thank you so much for your support. I think we can close this issue now.
