### ISSUE TITLE
Notifications about new on-call shift can't be sent to Slack channel

### ISSUE THREAD

**Issue by khanhtran1991** [grafana/oncall#1431]
Hello team,
After updating to the latest version (v1.1.29), notifications about new on-call shift can't be sent to the selected Slack channel.
It worked fine before. Please find the information below.

![Screenshot from 2023-03-01 17-19-17](https://user-images.githubusercontent.com/100182792/222111553-9b2c4462-8f12-4f7c-a789-96f9c0b9023d.png)

- Open Source OnCall
- v1.1.29
- `part:schedules`
- **bug**
- Please find the logs below
```
2023-03-01 09:41:28,719 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.schedules.tasks.refresh_ical_files.refresh_ical_file[be47c42f-2a42-4b53-b4aa-0a93faa39350] received
2023-03-01 09:41:28,726 source=engine:celery worker=ForkPoolWorker-4 task_id=f0f724a0-81ae-4849-924f-1f5370509ba1 task_name=apps.schedules.tasks.refresh_ical_files.start_refresh_ical_files name=celery.app.trace level=INFO Task apps.schedules.tasks.refresh_ical_files.start_refresh_ical_files[f0f724a0-81ae-4849-924f-1f5370509ba1] succeeded in 0.04729140701238066s: None
2023-03-01 09:41:28,731 source=engine:celery worker=ForkPoolWorker-4 task_id=dd0c813c-3a09-4b69-800e-22a2cbaf5b0b task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=apps.schedules.tasks.refresh_ical_files level=INFO Refresh ical files for schedule 46
2023-03-01 09:41:28,733 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.slack.tasks.start_update_slack_user_group_for_schedules[6bafaacc-235b-4d1a-ba47-daebac470a8c] received
2023-03-01 09:41:28,736 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.schedules.tasks.refresh_ical_files.refresh_ical_file[0e5434d1-362a-4c30-a08b-a8b8cd47dfb4] received
2023-03-01 09:41:28,839 source=engine:celery worker=ForkPoolWorker-4 task_id=a0f96c3b-dbef-404e-97f3-806b4a75216f task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=apps.schedules.tasks.refresh_ical_files level=INFO run_task_primary 53 False icals not equal
2023-03-01 09:41:28,840 source=engine:celery worker=ForkPoolWorker-4 task_id=a0f96c3b-dbef-404e-97f3-806b4a75216f task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=celery.app.trace level=ERROR Task apps.schedules.tasks.refresh_ical_files.refresh_ical_file[a0f96c3b-dbef-404e-97f3-806b4a75216f] raised unexpected: ValueError("Found no components where exactly one is required: ''")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/etc/app/apps/schedules/tasks/refresh_ical_files.py", line 60, in refresh_ical_file
    run_task_overrides = not is_icals_equal(
  File "/etc/app/apps/schedules/ical_utils.py", line 502, in is_icals_equal
    first_cal = Calendar.from_ical(first)
  File "/usr/local/lib/python3.9/site-packages/icalendar/cal.py", line 399, in from_ical
    raise ValueError('Found no components where '
ValueError: Found no components where exactly one is required: ''
2023-03-01 09:41:28,844 source=engine:celery worker=ForkPoolWorker-4 task_id=a8cea7da-32d7-4999-b523-e8ad0bfe645e task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=apps.schedules.tasks.refresh_ical_files level=INFO Refresh ical files for schedule 45
2023-03-01 09:41:28,845 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.schedules.tasks.refresh_ical_files.refresh_ical_file[1c38c75a-a8af-4662-9624-7090f02a1cd3] received
2023-03-01 09:41:28,918 source=engine:celery worker=ForkPoolWorker-4 task_id=a8cea7da-32d7-4999-b523-e8ad0bfe645e task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=apps.schedules.tasks.refresh_ical_files level=INFO run_task_primary 45 False icals not equal
2023-03-01 09:41:28,919 source=engine:celery worker=ForkPoolWorker-4 task_id=a8cea7da-32d7-4999-b523-e8ad0bfe645e task_name=apps.schedules.tasks.refresh_ical_files.refresh_ical_file name=celery.app.trace level=ERROR Task apps.schedules.tasks.refresh_ical_files.refresh_ical_file[a8cea7da-32d7-4999-b523-e8ad0bfe645e] raised unexpected: ValueError("Found no components where exactly one is required: ''")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/etc/app/apps/schedules/tasks/refresh_ical_files.py", line 60, in refresh_ical_file
    run_task_overrides = not is_icals_equal(
  File "/etc/app/apps/schedules/ical_utils.py", line 502, in is_icals_equal
    first_cal = Calendar.from_ical(first)
  File "/usr/local/lib/python3.9/site-packages/icalendar/cal.py", line 399, in from_ical
    raise ValueError('Found no components where '
ValueError: Found no components where exactly one is required: ''
```

**Comment by Konstantinov-Innokentii** [comment]
Hello @khanhtran1991, consider upgrade to the latest version, we fixed it in [1.1.30](https://github.com/grafana/oncall/releases/tag/v1.1.30)

**Comment by khanhtran1991** [comment]
Thanks for your support! I've updated to v1.1.32, and it really works :+1:
