### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'forward_from_chat'

### ISSUE THREAD

**Issue by artem-shestakov** [grafana/oncall#1584]
Hello!
Geting error in logs `AttributeError: 'NoneType' object has no attribute 'forward_from_chat'`

- Open Source OnCall.
- Plugins version v1.1.40

Logs:
```
2023-03-21 08:04:30 source=engine:app google_trace_id=none logger=apps.telegram.updates.update_manager Update from Telegram: {'update_id': 834244xxx, 'edited_message': {'forward_date': 1679089355, 'entities': [{'url': 'http://x.x.x.x:3000/a/grafana-oncall-app/?oncall-uuid=44f5f85a-024f-4435-82b1-78d23beac56b', 'offset': 0, 'type': 'text_link', 'length': 1}, {'offset': 69, 'type': 'url', 'length': 76}, {'offset': 147, 'type': 'bold', 'length': 6}, {'offset': 162, 'type': 'bold', 'length': 7}, {'offset': 320, 'type': 'bold', 'length': 12}], 'supergroup_chat_created': False, 'text': '\u200d⚪️ #45, DeadMansSwitch\nFiring, alerts: 680+\nSource: AlertManager 😊\nhttp://x.x.x.x:3000/a/grafana-oncall-app/?page=incident&id=IC9P4HX86KXGW\n\nStatus: firing\nLabels: \nevent: Heartbeat\nmonitor: x_collector\nservice: xxx\ntimeout: 1800\nseverity: critical\nalertname: DeadMansSwitch\ncollector: x_collector\nAnnotations:\nsummary: Alerting DeadMansSwitch\n\ndescription: This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline is functional.', 'new_chat_photo': [], 'chat': {'title': 'xxx monitoring Chat', 'type': 'supergroup', 'id': -1001979085xxx}, 'sender_chat': {'title': 'xxx monitoring', 'type': 'channel', 'id': -1001774825xxx}, 'forward_from_chat': {'title': 'xxx monitoring', 'type': 'channel', 'id': -1001774825xxx}, 'date': 1679089358, 'channel_chat_created': False, 'delete_chat_photo': False, 'edit_date': 1679299716, 'photo': [], 'is_automatic_forward': True, 'group_chat_created': False, 'forward_signature': 'xxx Monitoring', 'forward_from_message_id': 5, 'caption_entities': [], 'new_chat_members': [], 'message_id': 8, 'from': {'is_bot': False, 'first_name': 'Telegram', 'id': 777000}}}
2023-03-21 08:04:30 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /telegram/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/etc/app/apps/telegram/views.py", line 15, in post
    UpdateManager.process_request(request)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 47, in process_request
    cls.process_update(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 25, in process_update
    cls._update_entity_names(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 55, in _update_entity_names
    cls._update_channel_and_group_names(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 61, in _update_channel_and_group_names
    channel_chat_id = update.message.forward_from_chat.id
AttributeError: 'NoneType' object has no attribute 'forward_from_chat'
```

**Comment by Konstantinov-Innokentii** [comment]
@vadimkerr could you please take a look?

**Comment by pabclsn** [comment]
same here :)

**Comment by dzift** [comment]
Hi all! Has anyone found a way to solve this error?

```
2023-06-01 10:57:43 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /telegram/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/etc/app/apps/telegram/views.py", line 15, in post
    UpdateManager.process_request(request)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 47, in process_request
    cls.process_update(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 25, in process_update
    cls._update_entity_names(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 55, in _update_entity_names
    cls._update_channel_and_group_names(update)
  File "/etc/app/apps/telegram/updates/update_manager.py", line 61, in _update_channel_and_group_names
    channel_chat_id = update.message.forward_from_chat.id
AttributeError: 'NoneType' object has no attribute 'forward_from_chat'
```

**Comment by joeyorlando** [comment]
Hi there 👋  thanks for reporting this. This was addressed in https://github.com/grafana/oncall/pull/3622 and will be included in an upcoming release

**Comment by AMDTonyRyzen** [comment]
@joeyorlando Hi, can you help me please? 
During the new installation, I encountered such a problem. several messages were sent to discussion, but then the engine started throwing errors
provided part of the log in the file


[Enginelog.txt](https://github.com/grafana/oncall/files/15437243/Enginelog.txt)


Please tell me, is there a fix for this bug on the client side or an application-level problem? I am more than sure that the problem is not shooting due to the settings of the bot or the group, since at first the alerts are sent normally.
