### ISSUE TITLE
Self-host installation issue with docker-compose-like config

### ISSUE THREAD

**Issue by rvem** [grafana/oncall#1645]
`<Remove before publishing>`

Hi 👋, thank you for opening an issue!

Please make sure to add such an info to the issue description:

- [ ] Mention is it's about Cloud or Open Source OnCall.
- [ ] Add OnCall backend & frontend versions.
- [ ] Include labels starting with "part:". Like `part:alertflow` or `part:schedules`. Search for all `part:` labels and
      choose the closest one.
- [ ] Include labels like `bug` or `feature request`.
- [ ] If it's a bug, include logs, scheenshots, videos. As much specific info as possible.

Issues mising those items will be closed.

`</Remove before publishing>`

OnCall backend and frontend versions - `v1.1.41`.
Grafana version - `9.2.0`. Grafana instance is using Google-based OAuth2 for authentication.

I'm trying to setup OnCall with existing Grafana installation by providing
`GRAFANA_API_URL` and `ONCALL_API_URL` in the containers env using redis + sqlite.

When the backend is started, frontend shows that it is "Validating your plugin connection... "

At the same time backend `oncall` container reports the following errors in logs:
```
Mar 28 06:46:38 polis docker-oncall-start[3152662]: 2023-03-28 06:46:38 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/plugin/status
Mar 28 06:46:38 docker-oncall-start[3152662]: Traceback (most recent call last):
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Mar 28 06:46:38 docker-oncall-start[3152662]:     response = get_response(request)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Mar 28 06:46:38 docker-oncall-start[3152662]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 28 06:46:38 polis docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Mar 28 06:46:38 docker-oncall-start[3152662]:     return view_func(*args, **kwargs)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
Mar 28 06:46:38 docker-oncall-start[3152662]:     return self.dispatch(request, *args, **kwargs)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
Mar 28 06:46:38 docker-oncall-start[3152662]:     response = self.handle_exception(exc)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
Mar 28 06:46:38 docker-oncall-start[3152662]:     self.raise_uncaught_exception(exc)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Mar 28 06:46:38 docker-oncall-start[3152662]:     raise exc
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
Mar 28 06:46:38 docker-oncall-start[3152662]:     self.initial(request, *args, **kwargs)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
Mar 28 06:46:38 docker-oncall-start[3152662]:     self.check_permissions(request)
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
Mar 28 06:46:38 docker-oncall-start[3152662]:     if not permission.has_permission(request, self):
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/etc/app/apps/grafana_plugin/permissions.py", line 21, in has_permission
Mar 28 06:46:38 docker-oncall-start[3152662]:     context = json.loads(request.headers.get("X-Instance-Context"))
Mar 28 06:46:38 docker-oncall-start[3152662]:   File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
Mar 28 06:46:38 docker-oncall-start[3152662]:     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
Mar 28 06:46:38 docker-oncall-start[3152662]: TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by rvem** [comment]
Hmm, apparently, `ONCALL_API_URL` got screwed up. I re-installed everything from scratch and seems like it worked
