### ISSUE TITLE
OSS | http/500 when trying to change team's resources visibility using Teams and Access Settings 

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/oncall#1774]
OSS
Grafana v9.4.7 (4add91f03d)
Oncall plugin v1.2.11
Oncall backend v1.2.11

![image](https://user-images.githubusercontent.com/8307692/232751735-d314a587-85c3-4ae1-8c1c-7bf3e8cd889b.png)

getting following error in `oncall-engine` when hitting "save" button

```
2023-04-18 10:35:58 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/teams/TAYE3811S8Z7L                                                               
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response                                                                                                   
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view                                                                                                  
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)                                                                                                                                                         
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception                                                                                             
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 65, in update
    instance = self.get_object()
  File "/etc/app/./common/api_helpers/mixins.py", line 180, in get_object
    obj = queryset.get(public_primary_key=pk)
AttributeError: 'list' object has no attribute 'get'
2023-04-18 10:35:58 source=engine:app google_trace_id=none logger=root inbound latency=0.069018 status=500 method=PUT path=/api/internal/v1/teams/TAYE3811S8Z7L content-length=36 slow=0 user_id=1 org_id=1
2023-04-18 10:35:58 source=engine:uwsgi status=500 method=PUT path=/api/internal/v1/teams/TAYE3811S8Z7L latency=0.070256 google_trace_id=- protocol=HTTP/1.1 resp_size=372 req_body_size=36
```

**Comment by vadimkerr** [comment]
fixed in [v1.2.14](https://github.com/grafana/oncall/releases/tag/v1.2.14)
