### ISSUE TITLE
Bug: Alertmanager Templates not working when Slack or Telegram is disabled

### ISSUE THREAD

**Issue by roock** [grafana/oncall#1889]
Oncall OnPremise Dev branch

Steps to Reproduce:
- In `dev/.env.dev` set either `FEATURE_TELEGRAM_INTEGRATION_ENABLED=False` or `FEATURE_SLACK_INTEGRATION_ENABLED=False`
- Start Development Environment from dev branch according to the docs
- Open Integration Page and Add an Alertmanager Integration
- Open the Alert Templates Section
- The page doesn't load
- The logs contain the following lines

```
2023-05-08 12:47:32 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/alert_receive_channel_templates/CYJ2WTTKI6S5I
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/common/api_helpers/mixins.py", line 211, in retrieve
    return super().retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/apps/api/serializers/alert_receive_channel.py", line 346, in to_representation
    ret = self._get_templates_to_show(ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/apps/api/serializers/alert_receive_channel.py", line 373, in _get_templates_to_show
    response_data.pop(st)
KeyError: 'slack_title_template'
2023-05-08 12:47:32 source=engine:app google_trace_id=none logger=root inbound latency=0.0357 status=500 method=GET path=/api/internal/v1/alert_receive_channel_templates/CYJ2WTTKI6S5I content-length=0 slow=0 user_id=1 org_id=1 
```

part:chatops

**Comment by alexfun1** [comment]
Got the same with slack enabled and telegram disabled:

**Comment by renrutmas** [comment]
Also happening on version 1.2.30

**Comment by kranthikirang** [comment]
This requires a validation check before popping the response_data list in _get_templates_to_show.
