### ISSUE TITLE
Alert Templates doesn't  shows from a few helm chart release ago

### ISSUE THREAD

**Issue by manolooon** [grafana/oncall#2062]
- Open Source OnCall ( helm chart 1.2.32 ) 
- OnCall backend version 1.2.32 & frontend version  1.2.28.( their must both 1.2.32 )

I install latest version of chart oncall version 1.2.32 in a new and clean k8s cluster , because some time ago, the alert template section doesn't show correctly.

With a fresh and clean installation neither shows ok.

screenshot below shows wrong version of backend & frontend and issue of "alert templates" ( always shows "Loading..." and circles going around ) : 

![imagen](https://github.com/grafana/oncall/assets/57991495/55174bf8-88c5-4163-8213-6744dadd3799)

this screenshot shows my release helm history:

![imagen](https://github.com/grafana/oncall/assets/57991495/8566e682-4a00-45be-9d05-88e62475229a)

And this one ,show images version of containers:

![imagen](https://github.com/grafana/oncall/assets/57991495/a808c8db-40e2-4a9e-b963-70996cd3bb73)

Here, attach detail http code 500:

![imagen](https://github.com/grafana/oncall/assets/57991495/2f701db5-e245-4ba5-8af4-0e6564603af3)

I copy & paste in text too for documenting the issue:

NAME                       	NAMESPACE                       	REVISION	UPDATED                                 	STATUS  	CHART        	APP VERSION
xxxxxxxxxxoncall-lab	lab-grafana-xxxxxxxx	1       	2023-05-30 20:07:18.504017266 +0200 CEST	deployed	oncall-1.2.33	v1.2.33

yyyyyyyyyyyyyyyyoncall-lab-celery-5bb847f9c7-dfmgf:	grafana/oncall:v1.2.33, 
yyyyyyyyyyyyyyyyoncall-lab-engine-78b7bcdd9-gs96m:	grafana/oncall:v1.2.33,

part:bug
part:alerttemplates

**Comment by iskhakov** [comment]
@manolooon could you try to update the plugin version
<img width="1200" alt="Screenshot 2023-05-31 at 9 32 28 AM" src="https://github.com/grafana/oncall/assets/2262529/e61e6a99-30c5-4b99-9112-53475b72d33c">


also could you please share the logs from `...oncall-lab-engine...` pod

**Comment by manolooon** [comment]
Hi all!

Thanks a Lot @iskhakov  for your reply.

Attach a screenshot ,its shows that button "update" don't exists.


![imagen](https://github.com/grafana/oncall/assets/57991495/9ca7ac08-e258-4b19-8fef-54da79cbe795)


Here , post the engine logs when I did "click" in "alert template" section:


<PRE>2023-05-31 11:12:41 source=engine:app google_trace_id=none logger=root inbound latency=0.17227 status=200 method=GET path=/api/internal/v1/alert_receive_channels/C1CQIG7J4CJCB user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0 content-length=0 slow=0 user_id=1 org_id=1 org_slug=self_hosted_org 
2023-05-31 11:12:41 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/alert_receive_channels/C1CQIG7J4CJCB?from_organization=false latency=0.176826 google_trace_id=- protocol=HTTP/1.1 resp_size=3239 req_body_size=0
2023-05-31 11:12:41 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/alert_receive_channel_templates/C1CQIG7J4CJCB
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/common/api_helpers/mixins.py", line 215, in retrieve
    return super().retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/apps/api/serializers/alert_receive_channel.py", line 346, in to_representation
    ret = self._get_templates_to_show(ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/apps/api/serializers/alert_receive_channel.py", line 373, in _get_templates_to_show
    response_data.pop(st)
KeyError: 'slack_title_template'
2023-05-31 11:12:41 source=engine:app google_trace_id=none logger=root inbound latency=0.197252 status=500 method=GET path=/api/internal/v1/alert_receive_channel_templates/C1CQIG7J4CJCB user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0 content-length=0 slow=0 user_id=1 org_id=1 org_slug=self_hosted_org 
2023-05-31 11:12:41 source=engine:uwsgi status=500 method=GET path=/api/internal/v1/alert_receive_channel_templates/C1CQIG7J4CJCB latency=0.199329 google_trace_id=- protocol=HTTP/1.1 resp_size=329 req_body_size=0
</PRE>

**Comment by manolooon** [comment]
Wonderful!! @iskhakov  /  @Matvey-Kuk  thanks a lot to all and thanks to much to all team!

Will wait for release patiently :-)

**Comment by manolooon** [comment]
Hi Team!

I have install the new chart helm released , the version 1.2.34, and the alert templates shows correctly!!
But, the update button at oncall plugin section , doesn't appear yet.

Thanks!

**Comment by Schechev** [comment]
v 1.2.31 engine, v 1.2.35 plugin - Alert Templates doesn't shows
