### ISSUE TITLE
Legacy webhook cannot be copied

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#2604]
### What went wrong?

**What happened**:
  - Legacy migrated webhooks cannot be copied and saved from the UI if the password field is populated.

```
Traceback (most recent call last):
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msd/Development/oncall/engine/apps/api/serializers/webhook.py", line 81, in to_internal_value
    data["password"] = self.instance.password
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'password'
```

**What did you expect to happen**:
  - Make a copy of the legacy webhook should create a webhook in the new format

### How do we reproduce it?

1. Open Grafana OnCall and navigate to Outgoing webhooks
2. Select a (Legacy) webhook which has the password field populated
3. Choose `Make a copy` from the menu and give the copy a name
4. When you click Create it will give an error

### Grafana OnCall Version

v1.3.11

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

### Anything else to add?

Work around is to delete the contents of the password field, then make the copy.  Then edit the new copy and add the password back in.

**Comment by mderynck** [comment]
This also applies to the authorization header field
