### ISSUE TITLE
Error: POST https://grafana-oncall.url/api/v1/actions/ giving up after 6 attempts

### ISSUE THREAD

**Issue by agaibura-practicum** [grafana/oncall#2792]
### What went wrong?

**What happened**:
- retries reached limit on creating an action on an outgoing webhook.

**What did you expect to happen**:
- well-formatted error that can give me more explained answer what happened and how can i fix it.

### How do we reproduce it?

sample code in terraform:
```
resource "grafana_oncall_outgoing_webhook" "jira_create_spi" {
  name = "jira_create_spi"
  url = "https://companyname.atlassian.net/rest/api/2/issue/"
  authorization_header = "Authorization: Basic ${data.vault_generic_secret.selected.data.grafana_oncall_jira_token}]"
  data = jsonencode({
    fields = {
        project = {
            key = "SPI"
        }
        summary = "[unknown] - {{integration.name}} - {{ alert_payload.labels.alertname }}"
        description = "prom link: {{alert_payload.generatorUrl}}; link: {{ alert_payload.permalinks }}"
    }
  })
}


# jira create SPI
resource "grafana_oncall_escalation" "SRE_SPI_0" {
  provider = grafana
  escalation_chain_id = grafana_oncall_escalation_chain.SRE.id
  position = 0
  action_to_trigger = grafana_oncall_outgoing_webhook.jira_create_spi.id
}
```

so just write that code and run `terraform apply`.

### Grafana OnCall Version

1.3.23

### Product Area

Terraform

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

so, i dive into kibana logs and found out a traceback:

```


2023-08-15 08:01:15 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/v1/actions/
--

  | Aug 15, 2023 @ 10:01:15.385 | Traceback (most recent call last):

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner

  | Aug 15, 2023 @ 10:01:15.385 | response = get_response(request)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response

  | Aug 15, 2023 @ 10:01:15.385 | response = wrapped_callback(request, *callback_args, **callback_kwargs)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

  | Aug 15, 2023 @ 10:01:15.385 | return view_func(*args, **kwargs)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view

  | Aug 15, 2023 @ 10:01:15.385 | return self.dispatch(request, *args, **kwargs)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch

  | Aug 15, 2023 @ 10:01:15.385 | response = self.handle_exception(exc)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/etc/app/common/api_helpers/mixins.py", line 142, in handle_exception

  | Aug 15, 2023 @ 10:01:15.385 | return super().handle_exception(exc)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception

  | Aug 15, 2023 @ 10:01:15.385 | self.raise_uncaught_exception(exc)

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

  | Aug 15, 2023 @ 10:01:15.385 | raise exc

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch

  | Aug 15, 2023 @ 10:01:15.385 | response = handler(request, *args, **kwargs)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create

  | Aug 15, 2023 @ 10:01:15.385 | serializer.is_valid(raise_exception=True)

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 220, in is_valid

  | Aug 15, 2023 @ 10:01:15.385 | self._validated_data = self.run_validation(self.initial_data)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 419, in run_validation

  | Aug 15, 2023 @ 10:01:15.385 | value = self.to_internal_value(data)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 478, in to_internal_value

  | Aug 15, 2023 @ 10:01:15.385 | validated_value = validate_method(validated_value)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/etc/app/apps/public_api/serializers/action.py", line 65, in validate_data

  | Aug 15, 2023 @ 10:01:15.385 | rendered = template.render(

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render

  | Aug 15, 2023 @ 10:01:15.385 | self.environment.handle_exception()

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception

  | Aug 15, 2023 @ 10:01:15.385 | raise rewrite_traceback_stack(source=source)

  | Aug 15, 2023 @ 10:01:15.385 | File "<template>", line 1, in top-level template code

  | Aug 15, 2023 @ 10:01:15.385 | File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr

  | Aug 15, 2023 @ 10:01:15.385 | value = getattr(obj, attribute)

  | Aug 15, 2023 @ 10:01:15.385 | ^^^^^^^^^^^^^^^^^^^^^^^

  | Aug 15, 2023 @ 10:01:15.385 | jinja2.exceptions.UndefinedError: 'alert_group' is undefined

```

Sorry for formatting, but it's informational that actual problem is incorrect variable usage in template. So can we show that error?

**Comment by Matvey-Kuk** [comment]
@mderynck wdyt, will it be fixed by https://github.com/grafana/oncall/pull/2790?
