### ISSUE TITLE
Stuck in 'Validating your plugin connection' 

### ISSUE THREAD

**Issue by AnteKronos** [grafana/oncall#2841]
### What went wrong?

**What happened**:
After installing the oncall plugin on grafana and entering the oncall OSS installation url the plugin gets stuck with the message 'Validating your plugin connection', the problem didn't occur with a previous url, it worked correctly before the change.
 I already tried updating grafana, disabling and reinstalling the plugin but without success. 
The call to the url inserted at the path https://my.oncall.host/api/internal/v1/plugin/status fails with code 500
I have no way to re-enter the correct configuration and try again

**There is a bug [report]( https://github.com/grafana/oncall/discussions/2478)**

**What did you expect to happen**:
Working link of the plugin with on call

![image](https://github.com/grafana/oncall/assets/101885287/59dfad03-975e-4702-878d-7aa0a22301f3)

### How do we reproduce it?

Install the plugin
Attempt to insert configuration
'Validating your plugin connection' warning and 500 error appears

### Grafana OnCall Version

1.3.25

### Product Area

Other

### Grafana OnCall Platform?

Docker

### User's Browser?

Google Chrome

### Anything else to add?

I add the log from backend

`2023-08-21 11:40:35 source=engine:app google_trace_id=none logger=root inbound latency=0.028291 status=500 method=GET path=/api/internal/v1/plugin/status user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 content-length=0 slow=0
2023-08-21 11:40:35 source=engine:uwsgi status=500 method=GET path=/api/internal/v1/plugin/status latency=0.029279 google_trace_id=- protocol=HTTP/1.1 resp_size=329 req_body_size=0
2023-08-21 11:40:40 source=engine:app google_trace_id=none logger=apps.social_auth.middlewares SocialAuthAuthCanceledExceptionMiddleware.process_exception: the JSON object must be str, bytes or bytearray, not NoneType
2023-08-21 11:40:40 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/plugin/status
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/apps/grafana_plugin/permissions.py", line 20, in has_permission
    context = json.loads(request.headers.get("X-Instance-Context"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
`

**Comment by xom4ek** [comment]
Just fyi - problem with 
```yaml
x-instance-context: { "stack_id": "5", "org_id": "100" }
```

Today face same problem - create proxy between `grafana` and `oncall` add this header to all requests and everything start works fine.

**Comment by mderynck** [comment]
Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)
