### ISSUE TITLE
HeLm: upgrading  a rabbitmq enabled install fails from 1.3.26 to 1.3.27

### ISSUE THREAD

**Issue by bpedersen2** [grafana/oncall#2885]
### What went wrong?

**What happened**:
- a helm upgrade from 1.3.26 to 1.3.27  with broker type rabbitmq

The new engine does not start due to missing  redis configs

```
2023-08-28T09:21:04.578586030+02:00 redis.exceptions.ConnectionError: Error -2 connecting to none:6379. Name or service not known.
Mon, Aug 28 2023 9:21:04 am
2023-08-28 07:21:04 source=engine:app google_trace_id=none logger=root inbound latency=0.173661 status=500 method=GET path=/startupprobe/ user_agent=kube-probe/1.26 content-length=0 slow=0 
2023-08-28T09:21:04.578719884+02:00 2023-08-28 07:21:04 source=engine:uwsgi status=500 method=GET path=/startupprobe/ latency=0.178077 google_trace_id=- protocol=HTTP/1.1 resp_size=337 req_body_size=0
Mon, Aug 28 2023 9:21:14 am
2023-08-28 07:21:14 source=engine:app google_trace_id=none logger=apps.social_auth.middlewares SocialAuthAuthCanceledExceptionMiddleware.process_exception: Error -2 connecting to none:6379. Name or service not known.
Mon, Aug 28 2023 9:21:14 am
2023-08-28 07:21:14 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /startupprobe/
2023-08-28T09:21:14.431883332+02:00 Traceback (most recent call last):
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 707, in connect
Mon, Aug 28 2023 9:21:14 am
    sock = self.retry.call_with_retry(
Mon, Aug 28 2023 9:21:14 am
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-28T09:21:14.431914874+02:00   File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
Mon, Aug 28 2023 9:21:14 am
    return do()
Mon, Aug 28 2023 9:21:14 am
           ^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 708, in <lambda>
Mon, Aug 28 2023 9:21:14 am
    lambda: self._connect(), lambda error: self.disconnect(error)
Mon, Aug 28 2023 9:21:14 am
            ^^^^^^^^^^^^^^^
2023-08-28T09:21:14.431981517+02:00   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 974, in _connect
Mon, Aug 28 2023 9:21:14 am
    for res in socket.getaddrinfo(
Mon, Aug 28 2023 9:21:14 am
               ^^^^^^^^^^^^^^^^^^^
2023-08-28T09:21:14.431998279+02:00   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
Mon, Aug 28 2023 9:21:14 am
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-08-28T09:21:14.432008617+02:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
socket.gaierror: [Errno -2] Name or service not known
Mon, Aug 28 2023 9:21:14 am

Mon, Aug 28 2023 9:21:14 am
During handling of the above exception, another exception occurred:
2023-08-28T09:21:14.432059010+02:00 
Mon, Aug 28 2023 9:21:14 am
Traceback (most recent call last):
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-08-28T09:21:14.432075680+02:00     response = get_response(request)
Mon, Aug 28 2023 9:21:14 am
               ^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
Mon, Aug 28 2023 9:21:14 am
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mon, Aug 28 2023 9:21:14 am
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
2023-08-28T09:21:14.432109641+02:00     return self.dispatch(request, *args, **kwargs)
2023-08-28T09:21:14.432114877+02:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
2023-08-28T09:21:14.432125311+02:00     return handler(request, *args, **kwargs)
Mon, Aug 28 2023 9:21:14 am
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-28T09:21:14.432136385+02:00   File "/etc/app/engine/views.py", line 46, in get
Mon, Aug 28 2023 9:21:14 am
    if cache.get(AlertChannelDefiningMixin.CACHE_KEY_DB_FALLBACK) is None:
2023-08-28T09:21:14.432148207+02:00        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 30, in wrapped
2023-08-28T09:21:14.432158945+02:00     return method(self, client, key, *args, **kwargs)
Mon, Aug 28 2023 9:21:14 am
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 267, in get
Mon, Aug 28 2023 9:21:14 am
    return self._get(client, key, default)
2023-08-28T09:21:14.432182672+02:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 255, in _get
Mon, Aug 28 2023 9:21:14 am
    value = client.get(key)
2023-08-28T09:21:14.432201577+02:00             ^^^^^^^^^^^^^^^
2023-08-28T09:21:14.432206814+02:00   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1816, in get
2023-08-28T09:21:14.432211989+02:00     return self.execute_command("GET", name)
Mon, Aug 28 2023 9:21:14 am
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
Mon, Aug 28 2023 9:21:14 am
    conn = self.connection or pool.get_connection(command_name, **options)
Mon, Aug 28 2023 9:21:14 am
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1663, in get_connection
Mon, Aug 28 2023 9:21:14 am
    connection.connect()
Mon, Aug 28 2023 9:21:14 am
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 713, in connect
Mon, Aug 28 2023 9:21:14 am
    raise ConnectionError(self._error_message(e))
Mon, Aug 28 2023 9:21:14 am
redis.exceptions.ConnectionError: Error -2 connecting to none:6379. Name or service not known.
```

See https://github.com/grafana/oncall/commit/3783aeab6411e4625532b3b66c53251dda5e29fe#r125684572

**What did you expect to happen**:
- upgrade runs smoothly

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

1.3.26 ->1.3.27

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by bpedersen2** [comment]
Note : I worked around by switching to `brokertype:  redis`  as this was a very-low volume install anyway.

**Comment by joeyorlando** [comment]
we should (somehow) enforce that `broker.type` is specified if the broker is redis. I don't think the old behaviour of including `RABBITMQ_` and `REDIS_` env vars should be necessary (as only one broker is used).

**Comment by Brainpitcher** [comment]
> Note : I worked around by switching to `brokertype: redis` as this was a very-low volume install anyway.

Thanks! It worked for me too.

**Comment by bpedersen2** [comment]
> we should (somehow) enforce that `broker.type` is specified if the broker is redis. I don't think the old behaviour of including `RABBITMQ_` and `REDIS_` env vars should be necessary (as only one broker is used).

No, the problem is the rabittmq broker type, which also needs redis and the the redis config. 

so:  
brokertype: redis   ==> only redis is needed
brokertype  rabbitmq ==>  bot the rabbitmq config and the redis config are required.

**Comment by kuzaxak** [comment]
@joeyorlando Hey, could you rework a [commit](https://github.com/grafana/oncall/commit/3783aeab6411e4625532b3b66c53251dda5e29fe) please?

**Comment by joeyorlando** [comment]
this was patched in #2927 and should be released in the coming days in v1.3.30

**Comment by toolchainX** [comment]
@joeyorlando I come across the same issue, when will  v1.3.30 be released?  hope it is released as soon as possible, tks in advance!

**Comment by joeyorlando** [comment]
v1.3.30 was released yesterday, please upgrade to this chart version and retry. Thanks!
