### ISSUE TITLE
Can not work with external intranet Redis without auth

### ISSUE THREAD

**Issue by toolchainX** [grafana/oncall#2941]
### What went wrong?

**What happened**:
I can not deploy helm chart with an external redis without authentication password
I have to set password for the external redis instance or else the deployment will failed.
<img width="1420" alt="image" src="https://github.com/grafana/oncall/assets/1506482/e2129067-7d24-41d3-af50-913158131390">

but after the externalRedis.password is set. the redis client failed to send requests to the external redis client

```
2023-09-01 06:29:33 source=engine:app google_trace_id=none logger=root inbound latency=0.179276 status=500 method=GET path=/startupprobe/ user_agent=kube-probe/1.26 content-length=0 slow=0
2023-09-01 06:29:33 source=engine:uwsgi status=500 method=GET path=/startupprobe/ latency=0.181938 google_trace_id=- protocol=HTTP/1.1 resp_size=337 req_body_size=0
2023-09-01 06:29:43 source=engine:app google_trace_id=none logger=apps.social_auth.middlewares SocialAuthAuthCanceledExceptionMiddleware.process_exception: Client sent AUTH, but no password is set
2023-09-01 06:29:43 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /startupprobe/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/engine/views.py", line 46, in get
    if cache.get(AlertChannelDefiningMixin.CACHE_KEY_DB_FALLBACK) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 30, in wrapped
    return method(self, client, key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 267, in get
    return self._get(client, key, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis_cache/backends/base.py", line 255, in _get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1816, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1663, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 719, in connect
    self.on_connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 763, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 504, in read_response
    raise response
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set
```

**What did you expect to happen**:
helm chart deployment works expected with intranet redis without password authentication

### How do we reproduce it?

deploy helm chart with  an external intranet redis instance without  password authentication 

### Grafana OnCall Version

helm chart version 1.3.30

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by rknightion** [comment]
I worked around this by setting this in the chart (for elasticache without any auth)

```
env:
  - name: REDIS_USERNAME
    value: ""
  - name: REDIS_PASSWORD
    value: ""
  - name: REDIS_HOST
    value: "whatever.use1.cache.amazonaws.com"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PROTOCOL
    value: "redis"
```

**Comment by luvpreetsingh** [comment]
@rknightion I get this error while using the above config

```
W0926 20:43:32.481607   49925 warnings.go:70] spec.template.spec.containers[0].env[22].name: duplicate name "REDIS_PASSWORD"
W0926 20:43:32.481647   49925 warnings.go:70] spec.template.spec.containers[0].env[23].name: duplicate name "REDIS_HOST"
W0926 20:43:32.481658   49925 warnings.go:70] spec.template.spec.containers[0].env[24].name: duplicate name "REDIS_PORT"
Error: UPGRADE FAILED: failed to create patch: The order in patch list:
[map[name:REDIS_HOST value:10.68.81.92] map[name:REDIS_PORT value:6379] map[name:REDIS_PASSWORD value:] map[name:REDIS_PASSWORD valueFrom:map[secretKeyRef:map[key:redis-password name:prod-grafana-oncall-redis-external]]] map[name:REDIS_USERNAME value:] map[name:REDIS_PROTOCOL value:redis]]
 doesn't match $setElementOrder list:
[map[name:BASE_URL] map[name:SECRET_KEY] map[name:MIRAGE_SECRET_KEY] map[name:MIRAGE_CIPHER_IV] map[name:DJANGO_SETTINGS_MODULE] map[name:AMIXR_DJANGO_ADMIN_PATH] map[name:OSS] map[name:UWSGI_LISTEN] map[name:BROKER_TYPE] map[name:GRAFANA_API_URL] map[name:DATABASE_TYPE] map[name:DATABASE_HOST] map[name:DATABASE_PORT] map[name:DATABASE_NAME] map[name:DATABASE_USER] map[name:DATABASE_PASSWORD] map[name:REDIS_HOST] map[name:REDIS_PORT] map[name:REDIS_PASSWORD] map[name:REDIS_USERNAME] map[name:REDIS_PASSWORD] map[name:REDIS_HOST] map[name:REDIS_PORT] map[name:REDIS_PROTOCOL]]
 && failed to create patch: The order in patch list:
[map[name:REDIS_HOST value:10.68.81.92] map[name:REDIS_PORT value:6379] map[name:REDIS_PASSWORD value:] map[name:REDIS_PASSWORD valueFrom:map[secretKeyRef:map[key:redis-password name:prod-grafana-oncall-redis-external]]] map[name:REDIS_USERNAME value:] map[name:REDIS_PROTOCOL value:redis]]
 doesn't match $setElementOrder list:
[map[name:BASE_URL] map[name:SECRET_KEY] map[name:MIRAGE_SECRET_KEY] map[name:MIRAGE_CIPHER_IV] map[name:DJANGO_SETTINGS_MODULE] map[name:AMIXR_DJANGO_ADMIN_PATH] map[name:OSS] map[name:UWSGI_LISTEN] map[name:BROKER_TYPE] map[name:GRAFANA_API_URL] map[name:DATABASE_TYPE] map[name:DATABASE_HOST] map[name:DATABASE_PORT] map[name:DATABASE_NAME] map[name:DATABASE_USER] map[name:DATABASE_PASSWORD] map[name:REDIS_HOST] map[name:REDIS_PORT] map[name:REDIS_PASSWORD] map[name:REDIS_USERNAME] map[name:REDIS_PASSWORD] map[name:REDIS_HOST] map[name:REDIS_PORT] map[name:REDIS_PROTOCOL]]
```

Can you post your externalRedis config too?

**Comment by toolchainX** [comment]
found a workaround using helm config here
```
externalRedis:
  # having to config the following two fields or helm apply will fail
  host: place_holder 
  password: place_holder
env:
  # note that the following env will populated to every pod
  REDIS_URI: redis://10.0.0.12:6379/4
```
