### ISSUE TITLE
Migration Problem: Unable to create django_migrations table due to permission denied in postgres 15 version

### ISSUE THREAD

**Issue by lergor11** [grafana/oncall#3022]
### What went wrong?

I encountered an issue during the migration process when trying to create the django_migrations table. 

The error message indicates a "permission denied for schema" issue.

```
│   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema                          │
│     raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)                                           │
│ django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (permission denied for schema pu │
│ blic                                                                                                                                  │
│ LINE 1: CREATE TABLE "django_migrations" ("id" bigserial NOT NULL PR...                                                               │
│                      ^                                                                                                                │
│ )
```

### How do we reproduce it?

Deploy helm chart to Postgres 15 https://www.postgresql.org/about/news/postgresql-15-released-2526/

### Grafana OnCall Version

v1.3.35

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

How can I change the schema from 'public' to the one I want?
In Django, to change the database schema, you can use the "schema" parameter in the database configuration. 
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydatabase',
        'USER': 'myuser',
        'PASSWORD': 'mypassword',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'schema': 'mydesiredschema',
        },
    }
}
```

**Comment by agilob** [comment]
It's failing for me even in a public schema, database created like this:
```
CREATE DATABASE oncall WITH ENCODING UTF8;
CREATE USER oncall WITH ENCRYPTED PASSWORD 'oncall';
GRANT ALL PRIVILEGES ON DATABASE oncall to oncall;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO oncall;
```

```
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate During handling of the above exception, another exception occurred:
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate Traceback (most recent call last):
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/etc/app/manage.py", line 15, in <module>
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     execute_from_command_line(sys.argv)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     utility.execute()
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     self.fetch_command(subcommand).run_from_argv(self.argv)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     self.execute(*args, **cmd_options)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     output = self.handle(*args, **options)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 89, in wrapped
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     res = handle_func(*args, **kwargs)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 244, in handle
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     post_migrate_state = executor.migrate(
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate                          ^^^^^^^^^^^^^^^^^
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 91, in migrate
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     self.recorder.ensure_schema()
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate     raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (permission denied for schema public
release-oncall-engine-migrate-2023-10-26-08-21-19-dfw2k oncall-migrate LINE 1: CREATE TABLE "django_migrations" ("id" bigserial NOT NULL PR...
```

**Comment by agilob** [comment]
Login as user with root privileges and `ALTER DATABASE oncall OWNER TO oncall;`

**Comment by batazor** [comment]
I'm curious if this problem can be solved from the oncall side itself?

**Comment by agilob** [comment]
Looks like it's a change within postgres, so postgres specific installation instructions should be updated (or created)
https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

Basically, if you create a separate database for `grafana/oncall`, then initial migration must be run as owner of the schema. I'm no expert here, but I think by default it would be your admin/root user. To run initial migration as non-root user, the database must be owned by the `oncall` user and granting the user all permissions still won't help, must run `ALTER DATABASE oncall OWNER TO oncall;` 

This isn't a problem with oncall or django itself, but increased granularity of permissions and privileges in postgres.

**Comment by joeyorlando** [comment]
going to close this out as it appears to be a problem specific to postgres
