### ISSUE TITLE
Mobile QR code not working on oncalldev

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#3318]
### What went wrong?

**What happened**:
- oncalldev is not generating the qr code, instead it gives an error

**What did you expect to happen**:
- to get a qr code

### How do we reproduce it?

1. Open Grafana OnCall on oncalldev
2. Go to the user profile
3. Click on Mobile App Connection tab
4. Disconnect the app (if it's currently connected)
5. You get the error

### Grafana OnCall Version

Grafana v10.3.0-63137 (ffcaef9c17f55ad98690d70bb5953e1131361729)

### Product Area

Alert Flow & Configuration, Auth, Mobile App

### Grafana OnCall Platform?

I use Grafana Cloud

### Anything else to add?

```
An unexpected error happened
Details
Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined

    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3680)
    at div
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at div
    at div
    at div
    at i (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:222:47314)
    at f (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:222:47838)
    at div
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at div
    at div
    at div
    at i (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:222:47314)
    at f (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:222:47838)
    at c
    at div
    at g (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:295:45949)
    at c
    at div
    at div
    at div
    at d (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:674:78938)
    at div
    at K (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:674:140028)
    at ue (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:674:139616)
    at Y
    at ae (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:674:140205)
    at d (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:223:10589)
    at c
    at div
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at ke (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:26317)
    at me (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:23553)
    at me (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:25748)
    at div
    at div
    at c (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:658:712)
    at div
    at div
    at div
    at div
    at J (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:120:36548)
    at f (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:203:29692)
    at div
    at W (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:658:4402)
    at ud (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:5860:6778)
    at sr.<anonymous> (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:310:3107)
    at c
    at c
    at c
    at t
    at div
    at qt (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:6551:2031)
    at component
    at Suspense
    at i (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:203:118815)
    at Eo (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:372:333)
    at me (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:23553)
    at ua (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:205:4728)
    at In (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:205:10219)
    at fc (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:11773)
    at me (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:25748)
    at div
    at div
    at main
    at div
    at bs (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:369:2442)
    at ua (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:205:4728)
    at In (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:205:10219)
    at ln (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:205:9608)
    at wc (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:12072)
    at me (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:224:19718)
    at div
    at u (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:223:13293)
    at v (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:37:13822)
    at h (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:674:220669)
    at l (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:965:19926)
    at i (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:203:118815)
    at g (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:203:119324)
    at Te (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9494.a71dc6a8aa5d84ebdb61.js:183:530)
    at ci (https://grafana-assets.grafana.net/grafana/10.3.0-63137/public/build/9875.9fcca4e5568e5d37643c.js:383:127)
```

**Comment by joeyorlando** [comment]
closing as completed in https://github.com/grafana/oncall/pull/3347
