### ISSUE TITLE
Cannot get escalation chain

### ISSUE THREAD

**Issue by HoangViet144** [grafana/oncall#3846]
### What went wrong?

**What happened**:
- We cannot get escalation chain when visiting Escalation chain UI
- Grafana engine log displays:
```
2024-02-07 04:20:53 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/escalation_chains
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1055, "'oncall.alerts_escalationchain.public_primary_key' isn't in GROUP BY")
```

**What did you expect to happen**:
- No error, chains appear

### How do we reproduce it?

1. Install new oncall from helm chart with image tag v1.3.102
2. Integrate with grafana
3. Go to Oncall > Escalation chains

### Grafana OnCall Version

v1.3.102

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by HoangViet144** [comment]
It seems not to work with mariadb galery.
It works well on standalone mariadb. Thus I will close the MR
