### ISSUE TITLE
Helm - SecurityContext - cannot setgid() as non-root user

### ISSUE THREAD

**Issue by vptimmy** [grafana/oncall#445]
We are trying to install a test instance of onCall via the helm chart to our K8 cluster.   We do not allow our container to run as root.

We are getting the following error from grafana-oncall-engine when trying to deploy the chart:

```
2022-08-31 11:33:46 current working directory: /etc/app
2022-08-31 11:33:46 writing pidfile to /tmp/project-master.pid
2022-08-31 11:33:46 detected binary path: /usr/local/bin/uwsgi
2022-08-31 11:33:46 cannot setgid() as non-root user
```

Here is the helm/values.yaml I have been trying to deploy with.  Any suggestions are greatly appreciated!

```
podSecurityContext:
    fsGroup: 2000

init:
  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

ingress-nginx:
  enabled: false

grafana:
  enabled: false

cert-manager:
  enabled: false

rabbitmq:
  enabled: true

redis:
  enabled: true

mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: oncall
```

**Comment by juris** [comment]
The issue still persists with chart version 1.0.5 and app version 1.0.35. I've just uncommented the default helm values:
```
podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

init:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: false
    runAsGroup: 1337
    runAsNonRoot: true
    runAsUser: 1337
```

**Comment by CactusZ** [comment]
Same issue for us, would be good to have a fix for that!

**Comment by anlight** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/12930183/200177249-dbde2260-7c53-4362-ada2-b794875a4aa0.png">

**Comment by isnt** [comment]
I made it work with this configuration (chart and app version: `1.2.21`):
```
# just commented out
podSecurityContext:
  fsGroup: 2000

# some modifications
securityContext:
  capabilities:
    drop:
    - ALL
    add:
    - SETGID
    - SETUID
  readOnlyRootFilesystem: false

# just commented out
init:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 1337
    runAsNonRoot: true
    runAsUser: 1337

```
I haven't checked further, but I think [uwsgi.ini](https://github.com/grafana/oncall/blob/c158c8f28bc41deaae4700632b8d2d88f0aacf2a/engine/uwsgi.ini#L9-L10) has to be modified before the `engine` container can be run without adding SETGID/SETUID capability to the container.

Without `SETGID`/`SETUID`, I've got the following error in the `engine` container:
```
❯ k -n grafana-oncall logs -l app.kubernetes.io/component=engine
Defaulted container "oncall" out of: oncall, wait-for-db (init)
Defaulted container "oncall" out of: oncall, wait-for-db (init)
2023-05-19 13:45:29 source=engine:uwsgi status=200 method=GET path=/health/ latency=0.001152 google_trace_id=- protocol=HTTP/1.1 resp_size=180 req_body_size=0
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=apps.slack.views Request id: 23df68df5d067f43678d47980a1885ec
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=apps.slack.views team_id: T6DRXNY78 channel_id: None user_id: None command: None event: user_change
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=apps.slack.views Organization: None
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=apps.slack.views SlackUserIdentity detected: None
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=apps.slack.views Event user_change. Dropping request because it does not have SlackUserIdentity.
2023-05-19 13:45:35 source=engine:app google_trace_id=none logger=root inbound latency=0.011722 status=200 method=POST path=/slack/event_api_endpoint/ content-length=1652 slow=0
2023-05-19 13:45:35 source=engine:uwsgi status=200 method=POST path=/slack/event_api_endpoint/ latency=0.012613 google_trace_id=- protocol=HTTP/1.1 resp_size=214 req_body_size=1652
2023-05-19 13:45:38 source=engine:app google_trace_id=none logger=root inbound latency=0.000408 status=200 method=GET path=/ content-length=0 slow=0
2023-05-19 13:45:38 source=engine:uwsgi status=200 method=GET path=/ latency=0.001022 google_trace_id=- protocol=HTTP/1.1 resp_size=223 req_body_size=0
2023-05-19 13:45:28 machine: x86_64
2023-05-19 13:45:28 clock source: unix
2023-05-19 13:45:28 detected number of CPU cores: 16
2023-05-19 13:45:28 current working directory: /etc/app
2023-05-19 13:45:28 writing pidfile to /tmp/project-master.pid
2023-05-19 13:45:28 detected binary path: /usr/local/bin/uwsgi
2023-05-19 13:45:28 !!! no internal routing support, rebuild with pcre support !!!
2023-05-19 13:45:28 uWSGI running as root, you can use --uid/--gid/--chroot options
2023-05-19 13:45:28 setgid() to 2000
2023-05-19 13:45:28 setgid(): Operation not permitted [core/utils.c line 836]
```

With `readOnlyRootFilesystem: true` the error was:
```
❯ k -n grafana-oncall logs -l app.kubernetes.io/component=celery
+ celery --quiet -A engine worker --concurrency=1 --max-tasks-per-child=100 -Q default,critical,long,slack,telegram,webhook,celery --beat -l info
2023-05-19 12:55:25,218 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker level=CRITICAL Unrecoverable error: FileNotFoundError(2, "No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/etc/app']")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
  File "/usr/local/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
    return super()._create_worker_process(i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1142, in _create_worker_process
    on_ready_counter = self._ctx.Value('i')
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/context.py", line 181, in Value
    return Value(typecode_or_type, *args, lock=lock,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/sharedctypes.py", line 78, in Value
    obj = RawValue(typecode_or_type, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/sharedctypes.py", line 46, in RawValue
    obj = _new_value(type_)
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/sharedctypes.py", line 37, in _new_value
    wrapper = heap.BufferWrapper(size)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/heap.py", line 274, in __init__
    block = BufferWrapper._heap.malloc(size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/heap.py", line 255, in malloc
    (arena, start, stop) = self._malloc(size)
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/heap.py", line 152, in _malloc
    arena = Arena(length)
            ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/heap.py", line 79, in __init__
    dir=util.get_temp_dir(),
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/util.py", line 146, in get_temp_dir
    tempdir = tempfile.mkdtemp(prefix='pymp-')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 357, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 126, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 299, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 292, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/etc/app']


❯ k -n grafana-oncall logs -l app.kubernetes.io/component=engine
2023-05-19 12:55:02 os: Linux-5.10.161+ #1 SMP Thu Jan 5 22:49:42 UTC 2023
2023-05-19 12:55:02 nodename: oncall-engine-74688d89fd-mz7dt
2023-05-19 12:55:02 machine: x86_64
2023-05-19 12:55:02 clock source: unix
2023-05-19 12:55:02 detected number of CPU cores: 16
2023-05-19 12:55:02 current working directory: /etc/app
2023-05-19 12:55:02 writing pidfile to /tmp/project-master.pid
2023-05-19 12:55:02 open("/tmp/project-master.pid"): Read-only file system [core/utils.c line 3624]

``` 

With `runAsNonRoot: true` and `runAsUser: 1000` the error was: 

```
❯ k logs -n grafana-oncall -l app.kubernetes.io/component=engine
Defaulted container "oncall" out of: oncall, wait-for-db (init)
[uWSGI] getting INI configuration from uwsgi.ini
[log-encoder] registered format ${strftime:%Y-%m-%d %H:%M:%S} ${msgnl}
2023-05-19 13:37:27 *** Starting uWSGI 2.0.21 (64bit) on [Fri May 19 13:37:27 2023] ***
2023-05-19 13:37:27 compiled with version: 8.3.0 on 10 May 2023 21:59:31
2023-05-19 13:37:27 os: Linux-5.10.161+ #1 SMP Thu Jan 5 22:49:42 UTC 2023
2023-05-19 13:37:27 nodename: oncall-engine-6f5f64bc9c-twwbz
2023-05-19 13:37:27 machine: x86_64
2023-05-19 13:37:27 clock source: unix
2023-05-19 13:37:27 detected number of CPU cores: 16
2023-05-19 13:37:27 current working directory: /etc/app
2023-05-19 13:37:27 writing pidfile to /tmp/project-master.pid
2023-05-19 13:37:27 detected binary path: /usr/local/bin/uwsgi
2023-05-19 13:37:27 !!! no internal routing support, rebuild with pcre support !!!
2023-05-19 13:37:27 cannot setgid() as non-root user

```
