### ISSUE TITLE
slack integration oncall 500 error

### ISSUE THREAD

**Issue by unfeeling91** [grafana/oncall#960]
Hi! For some reason slack integration does not work, in logs I see
`2022-12-07 16:26:11 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /slack/event_api_endpoint/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/etc/app/apps/slack/views.py", line 129, in post
    SlackEventApiEndpointView.verify_signature(
  File "/etc/app/apps/slack/views.py", line 107, in verify_signature
    request_hash = "v0=" + hmac.new(str.encode(secret), req, hashlib.sha256).hexdigest()
TypeError: descriptor 'encode' for 'str' objects doesn't apply to a 'NoneType' object`

**Comment by Matvey-Kuk** [comment]
@unfeeling91 please provide details about environment, use-case, steps how to reproduce.

**Comment by unfeeling91** [comment]
oncall installed via helm chart, chart version 1.1.0
grafana 9.3.1
oncall 1.1.5
in chart parameters provided

`slack:
      # enabled enable the Slack ChatOps integration for the Oncall Engine.
      enabled: true
      # command sets the Slack bot slash-command
      command: oncall
      # clientId configures the Slack app OAuth2 client ID.
      # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Client ID
      clientId: secretidvalue
      # clientSecret configures the Slack app OAuth2 client secret.
      # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Client Secret
      clientSecret: secretclientvalue
      # signingSecret configures the Slack app signature secret used to sign
      # requests comming from Slack.
      # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Signing Secret
      signingSecret: secretsigning
      # OnCall external URL`

I follow instructions on page https://grafana.com/docs/oncall/latest/open-source/

**Comment by ipower-cc** [comment]
I've managed to trip on the same exception, when integrating OnCall into an pre-existing Grafana deployment.

```
oncall-engine-1        |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
oncall-engine-1        |     response = handler(request, *args, **kwargs)
oncall-engine-1        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
oncall-engine-1        |   File "/etc/app/apps/slack/views.py", line 113, in post
oncall-engine-1        |     SlackEventApiEndpointView.verify_signature(
oncall-engine-1        |   File "/etc/app/apps/slack/views.py", line 91, in verify_signature
oncall-engine-1        |     request_hash = "v0=" + hmac.new(str.encode(secret), req, hashlib.sha256).hexdigest()
oncall-engine-1        |                                     ^^^^^^^^^^^^^^^^^^
oncall-engine-1        | TypeError: descriptor 'encode' for 'str' objects doesn't apply to a 'NoneType' object
oncall-engine-1        | 2023-11-23 20:07:04 source=engine:app google_trace_id=none logger=root inbound latency=0.436642 status=500 method=POST path=/slack/event_api_endpoint/ user_agent=Slackbot 1.0 (+https://api.slack.com/robots) content-length=129 slow=0 
```

If I run the engine django app with an IDE debugger and comment out the HTTP_X_SLACK_ header checks, sending a fake POST to /slack/event_api_endpoint/  runs well enough to not crash, and returns a 403.
I don't quite understand the way str.encode() is working here, the crypto etc. But it seems like I have all the SLACK_ environment variables set correctly.

I can reproduce the problem by going to my slack app's Event Subscriptions configuration https://api.slack.com/apps/AxxxxxxxxxP/event-subscriptions?  and using the retry feature to POST to https://oncall.xxxxxxxx.net/slack/event_api_endpoint/

I'm installing Oncall into a mixed architecture of VPS and containers, using using docker-compose (file attached) and docker host networking.  
[docker-compose.txt](https://github.com/grafana/oncall/files/13453337/docker-compose.txt)

Postgres database.  I don't have an MQ service going yet. DJANGO_SETTINGS_MODULE is set to 'settings.hobby'

Environment var dump from the engine container:

```
EMAIL_HOST_PASSWORD=3idQxxxxxxxxxxxxxxxxxxxxxxxxxM1ok
SLACK_SIGNING_SECRET=d4e7xxxxxxxxxxxxxxxxxxxxxx7f7d20f7
EMAIL_PORT=587
TELEGRAM_WEBHOOK_HOST=
EMAIL_HOST_USER=alert-bot@xxxxx.com
DATABASE_HOST=o02-vpc
TELEGRAM_TOKEN=
EMAIL_HOST=smtp-relay.gmail.com
BROKER_TYPE=redis
DATABASE_USER=gfocadm
FEATURE_SLACK_INTEGRATION_ENABLED=true
DATABASE_TYPE=postgresql
SLACK_CLIENT_OAUTH_SECRET=c48a44xxxxxxxxxxxxxxxxxxxx9471dd5
DATABASE_PASSWORD=ru5Q2xxxxxxxxxxxxxyUSB3c
DJANGO_SETTINGS_MODULE=settings.hobby
BASE_URL=http://o03-vpc:7000
FEATURE_TELEGRAM_INTEGRATION_ENABLED=false
REDIS_URI=redis://o03-vpc:6402/0
GRAFANA_API_URL=http://o03-vpc:3001
EMAIL_FROM_ADDRESS=noreply@xxxxx.com
DATABASE_NAME=oncall
SECRET_KEY=#y$@cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyi&mlkxy
SLACK_CLIENT_OAUTH_ID=840xxxxxxx74.62xxxxxxxx669
SLACK_INSTALL_RETURN_REDIRECT_HOST=https://oncall.xxxxx.net
APP_USER=appuser
prometheus_multiproc_dir=/tmp/prometheus_django_metrics
HOME=/
```

I've attached a run log from the docker-compose stack that includes the apps/slack/views.py exception / stack trace.
[oncall-hobby-services.log](https://github.com/grafana/oncall/files/13453322/oncall-hobby-services.log)

My guess is I'm missing some kind of env-related setting that is only found in the helm charts, but it's just a guess. Along those lines, I'm a little confused by the difference between SLACK_SIGNING_SECRET vs SLACK_SIGNING_SECRET_LIVE.

**Comment by novotnej** [comment]
Hello, I am stuck on the same issue. 
Installed with helm chart (1.5.1), 
Kubernetes 1.29
Created a new slack app using the manifest (as per https://grafana.com/docs/oncall/latest/set-up/open-source/#slack-setup)
SLACK_CLIENT_OAUTH_ID 
SLACK_CLIENT_OAUTH_SECRET 
SLACK_INSTALL_RETURN_REDIRECT_HOST 
SLACK_SIGNING_SECRET 

are all filled in, 

when I GET /slack/event_api_endpoint/ I get "hello"
but Slack's POSTs end in 500

The Envs dashboard shows the values as "Empty", despite the value clearly being there
![image](https://github.com/grafana/oncall/assets/3701992/6496ca82-3dd3-4cbb-a78b-6f90e9a20798)

**Comment by novotnej** [comment]
And this here is a workaround, you need to click on "Reset to defaults". I think this is still a bug, though, that the values configured via ENV are not applied automatically

https://github.com/grafana/oncall/issues/4262

**Comment by ipower-cc** [comment]
Just wanted to followup that the ENV dashboard UI workaround mentioned in #4262 was the crux of my problem as well.
After weeks of experimentation I eventually figured out that clearing the settings in the UI allowed the environment variables I was setting to take precedence. At that point I wasn't clear how the database was also involved, or what default is supposed to mean in what context, and didn't care. Just happy to be past the voodoo.

If changing the configuration behavior is difficult, a log message warning about empty string values for crucial settings (say during initialization) would have helped me to see the problem much sooner.

**Comment by lustsazeus-lab** [comment]
Thanks for the detailed reports here — the stack trace points to `secret` being `None` in `verify_signature`, which usually means the signing secret is not being resolved from env at runtime (or an empty value in DB/UI is overriding env).

A quick triage path that has worked for similar cases:
1. Verify `SLACK_SIGNING_SECRET` is present in the *engine* process env (not only web/worker), and not empty.
2. In OnCall UI env settings, clear/reset conflicting Slack fields so env values take precedence.
3. Restart engine after env/UI changes, then replay Slack Event Subscriptions request.
4. Add a guard in `apps/slack/views.py` before `str.encode(secret)` to return explicit 4xx + log when secret is missing, instead of 500.

If maintainers want, I can provide a small PR with:
- defensive nil-check + clearer error message,
- precedence/override notes in docs,
- regression test for missing/empty signing secret path.

Happy to prepare a concrete patch plan if you share current version + deploy mode (helm/docker-compose).

**Comment by lustsazeus-lab** [comment]
I can help triage + fix this. If you can share:
1) OnCall version/commit + how you deploy (docker-compose/K8s)
2) OnCall logs/stacktrace around the 500 (redact secrets) + the exact Slack event payload triggering it
3) Your Slack app settings (Event Subscriptions URL + scopes) and whether you're using OSS or Cloud

I can propose a minimal patch + add an integration/API-contract test so it doesn’t regress.
If you want a paid fast‑track: I can deliver a PR + tests within 48h for a fixed USD 599 (or USD 999 if it needs a broader refactor). What’s the preferred sponsor/payment/invoice path for this repo (GitHub Sponsors / contract / other)?
