### ISSUE TITLE
500 error while trying to install the plugin

### ISSUE THREAD

**Issue by AlexZalyalowa** [grafana/oncall#966]
Hello there!
I have a separate Grafana installation that I'm trying to connect to the OnCall install that I did with Helm. 
grafana v.9.2.4
oncall helm chart v.1.1.5
When I'm trying to install the plugin, I get this error in grafana ui
`
An unknown error occured when trying to install the plugin. Are you sure that your OnCall API URL, http://oncall-engine:8080, is correct?
Refresh your page and try again, or try removing your plugin configuration and reconfiguring.
`
and these errors in oncall engine logs
`
2022-12-08 15:01:40 source=engine:app google_trace_id=none logger=root outbound latency=0.0004486348479986191 status=503 method=HEAD url=api/org slow=0 
2022-12-08 15:01:40 source=engine:app google_trace_id=none logger=django.request Internal Server Error: /api/internal/v1/plugin/self-hosted/install
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/etc/app/apps/grafana_plugin/views/self_hosted_install.py", line 33, in post
    _, client_status = grafana_api_client.check_token()
  File "/etc/app/apps/grafana_plugin/helpers/client.py", line 79, in check_token
    return self.api_head("api/org")
  File "/etc/app/apps/grafana_plugin/helpers/client.py", line 27, in api_head
    return self.call_api(endpoint, requests.head, body)
  File "/etc/app/apps/grafana_plugin/helpers/client.py", line 38, in call_api
    response = http_method(call_status["url"], json=body, headers=self.request_headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'api/org': No scheme supplied. Perhaps you meant http://api/org?
2022-12-08 15:01:40 source=engine:app google_trace_id=none logger=root inbound latency=0.074455 status=500 method=POST path=/api/internal/v1/plugin/self-hosted/install content-length=0 slow=0 
2022-12-08 15:01:40 source=engine:uwsgi status=500 method=POST path=/api/internal/v1/plugin/self-hosted/install latency=0.075285 google_trace_id=- protocol=HTTP/1.1 resp_size=329 req_body_size=0
`

**Comment by joeyorlando** [comment]
hi there 👋 

what is the value you are using for [`externalGrafana.url`](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml#L298-L299) in your deployed chart?

This line in your stack trace:
```bash
requests.exceptions.MissingSchema: Invalid URL 'api/org': No scheme supplied. Perhaps you meant http://api/org?
```
leads me to believe that this value might not be set. It should be set to the hostname of your grafana instance. This URL should also be able to be reached from your OnCall backend.

**Comment by lusid** [comment]
I got the same `MissingSchema` error when I attempted this with the new v1.1.0 release of the OnCall helm chart. My issue was that I didn't include the transport protocol in the `externalGrafana.url` value. After including `https://`, it worked.
